# -*- coding: utf-8 -*-
{
    "name": "Viet education",
    "version": "1.0",
    "summary": "Development education with Viet Vu",
    "description": "Update fields for product",
    "category": "zen8labs/zen8labs",
    "author": "zen8labs",
    "website": "https://www.zen8labs.com",
    "depends": ["base", "z_web", "website", "z_hr", "z_partner", "web"],
    "data": [
        'security/security.xml',
        'security/ir.model.access.csv',
        'report/report.xml',
        # 'views/owl_student_api_view.xml',
        'views/owl_student_templates.xml',
        'data/sequence.xml',
        'data/email_template.xml',
        'data/cron.xml',
        'wizard/dropout_school.xml',
        'views/education_class_group.xml',
        'views/res_partner.xml',
        'views/education_student_views.xml',
        'views/student_level_views.xml',
        'views/education_class_schedule_views.xml',
        'views/education_admission_report.xml',
        'views/education_class_views.xml',
        'views/education_student_todolist.xml',
        'views/education_school.xml',
        'views/menu.xml',
        'views/template.xml',  
        'report/student_card.xml',
    ],
    "assets": {
        "web.assets_backend": [
            'v_education/static/src/views/todo_list/todo_list.xml',
            'v_education/static/src/views/todo_list/todo_list.js',
            # 'v_education/static/src/views/student_form/owl_student_api_view.xml',
            # 'v_education/static/src/views/student_form/owl_student_form.js',
            # 'v_education/static/src/views/*/*.js',
            # 'v_education/static/src/views/*/*.xml',
            # 'v_education/static/src/student_form/*.scss',
        ]
    },
    "installable": True,
    "license": "LGPL-3",
}
