{
    "name": "Viet education",
    "version": "1.0",
    "summary": "Development education with Viet Vu",
    "description": "Update fields for product",
    "category": "zen8labs/zen8labs",
    "author": "zen8labs",
    "website": "https://www.zen8labs.com",
    "depends": ["base", "z_web", "website", "web"],
    "data": [
        'security/security.xml',
        'security/ir.model.access.csv',
        'report/report.xml',
        'data/sequence.xml',
        'data/email_template.xml',
        'data/cron.xml',
        'wizard/dropout_school.xml',
        'views/education_class_group.xml',
        'views/res_partner.xml',
        'views/education_student_views.xml',
        'views/student_level_views.xml',
        'views/education_class_schedule_views.xml',
        'views/education_admission_report.xml',
        'views/education_class_views.xml',
        'views/education_student_todolist.xml',
        'views/education_school.xml',
        'views/menu.xml',
        'views/template.xml',  
        'report/student_card.xml',
    ],
    "assets": {
        "web.assets_frontend": [
            '/v_education/static/src/js/studentform.js',      
        ],
        "web.assets_backend": [
            # '/v_education/static/src/components/view_inheritance/res_partner_kanban_view.xml',
            '/v_education/static/src/components/todo_list.xml',
            # '/v_education/static/src/components/view_inheritance/res_partner_kanban_view.js',
            '/v_education/static/src/components/todo_list.js',
            '/v_education/static/src/components/todo_list.scss',
        ],
        'web.assets_qweb': [
            'v_education/static/src/xml/student_templates.xml',
        ],
    },
    "installable": True,
    "license": "LGPL-3",
}
